# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('started_at', models.DateTimeField(verbose_name='Started at')),
                ('ended_at', models.DateTimeField(verbose_name='Ended at')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', related_query_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
