# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpug', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='place',
            field=models.CharField(default=None, max_length=255, verbose_name='Place'),
            preserve_default=False,
        ),
    ]
